version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "makeChange"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1egjp77e99tqq"
s3_prefix = "makeChange"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=243012589631.dkr.ecr.us-east-1.amazonaws.com/makechangefb6e15d5/helloworldfunction19d43fc4repo"]
